#!/usr/bin/env ruby
# frozen_string_literal: true

require 'scelint'

to_check = ARGV.empty? ? ['.'] : ARGV
lint = Scelint::Lint.new(to_check)

count = lint.files.count

if count.zero?
  warn 'No SCE data found.'
  exit 0
end

lint.errors.each do |error|
  warn "ERROR: #{error}"
end

lint.warnings.each do |warning|
  warn "WARNING: #{warning}"
end

lint.notes.each do |note|
  warn "NOTE: #{note}"
end

message = "Checked #{count} files."
if lint.errors.count == 0
  message += '  No errors.'
  exit_code = 0
else
  message += "  #{lint.errors.count} errors."
  exit_code = 1
end

message += "  #{lint.warnings.count} warnings." if lint.warnings.count > 0

message += " #{lint.notes.count} notes." if lint.notes.count > 0

puts message
exit exit_code
