---
name: 'PR tests'
on:
  - pull_request

jobs:

  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - run: bundle exec rake spec
